css-canvas-medical-pg1//MichaelCardona
MichaelCardona/m1-321-code-solutions pull request #26
Opened 2021-03-31 03:20 UTC by MichaelCardona

![CSS_canvas](https://user-images.githubusercontent.com/39914462/113085766-4f359b80-9195-11eb-81eb-f8f5f1eda033.gif)

2021-03-31 03:45 UTC, Zhiwutian requested changes
Hey Michael, very nice initial submission, please note the code comments, and here are a few visual ones:
1. The image is a little too dark, I would lighten
2. The button color and Canvas logo need to be modified to match the example
3. The background color of the `clinicians prefer canvas` should be a light gray to match the example
4. A couple of sections seem to have blue fonts, those should be update to match the example
5. The line at the top of the page should be as wide as the container, not the whole page width.

Keep up the good work!

2021-03-31 03:45 UTC, Zhiwutian commented on css-canvas-medical/index.html
> +<div class="top-container">
I would recommend having one single container which contains the other sections. so essentially just adding one parent layer to the current structure to contain all of the `rows`

2021-03-31 03:45 UTC, Zhiwutian commented on css-canvas-medical/index.html
> +    <p class="top-right"> Product Implementation About Us Blog </p>
While this does recreate the look, you want to use a `ul` here with lis for the links.

2021-03-31 03:45 UTC, Zhiwutian commented on css-canvas-medical/styles.css
> +  float: left;
you typically don't want to combine float with flexbox when doing layouts. That does not mean you can't use float, but as you are using `flex` everywhere else, it does help with the consistency to use it for these elements.

2021-03-31 03:45 UTC, Zhiwutian commented on css-canvas-medical/styles.css
> +  left: 400px;
this is a lot of left to use, it might be better to set flex on the parent and use it to control the child element

2021-03-31 03:45 UTC, Zhiwutian commented on css-canvas-medical/styles.css
> +  display: flex;
This seems to be setting flex on an element which has no children, which would mean any flex properties would have no effect. Make sure your selectors are selecting the right elements.

2021-03-31 03:45 UTC, Zhiwutian commented on css-canvas-medical/index.html
> +<div class="last-content-row">
be careful with names like `last-content-row` when there are more rows to come. I do stuff like this often, but make sure you go back and update names for semantic clarity!

2021-03-31 03:45 UTC, Zhiwutian commented on css-canvas-medical/index.html
> +<div class="first-section">
a `row` class for each of these sections might help distinguish each section separation, or I would make the naming convention consistent:
first-section, second-section, third-section, etc

2021-04-03 20:23 UTC, MichaelCardona commented
![CSS_canvas_Update](https://user-images.githubusercontent.com/39914462/113490562-ba29ef80-947f-11eb-844f-4538f0fa5a81.gif)

2021-04-03 20:41 UTC, Zhiwutian approved these changes
👍

2021-04-06 02:30 UTC, merged